[package]
name = "warshall_algorithm_study"
version = "0.1.0"
authors = ["LiangJiaDong <2530604880@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
